### ISSUE TITLE
Games crash on unc0ver ios 14.2

### ISSUE THREAD

**Issue by QcSamuel** [brendonjkding/Unity60FPS#2]
when i enable the tweak on a game it will crash on launch even with the set fps on first touch disabled.

device: iphone 11
ios build: 14.2
jailbreak: unc0ver 6.0.1

**Comment by QcSamuel** [comment]
tried alot of unity games and only one doesnt crash so maybe it's not unc0ver and some incompatibility with the unity version that games use

**Comment by brendonjkding** [comment]
What is the names of crashed games.

**Comment by QcSamuel** [comment]
MiniDayz2, Guns n spurs, crazy Bikers 3, Gunshot City

**Comment by brendonjkding** [comment]
I tested Gunshot City and found it doesn't export `Application.targetFrameRate` . Unfortunately this tweak can't work without it. I think other games may be the same.

**Comment by QcSamuel** [comment]
the callbackFramerateChange:(int) ?

**Comment by brendonjkding** [comment]
More specifically, this tweak works by searching and hooking `UnityEngine.Application::set_targetFrameRate`.

**Comment by QcSamuel** [comment]
going to close this issue then you can reopen it if you want to
