### ISSUE TITLE
Is it possible that we get the latest deb?

### ISSUE THREAD

**Issue by phoenix5980** [brendonjkding/Unity60FPS#5]
I tried to find the latest deb but only got to find [this old deb](http://apt.thebigboss.org/onepackage.php?bundleid=com.brend0n.fgotw60fps&db=). I wonder if it’s possible to use [this sign tool](https://github.com/SignTools/SignTools) to inject the this deb into unjailbroken devices.

**Comment by brendonjkding** [comment]
Inline hooks which is necessary for this tweak to work are NOT supported by unjailbroken devices.
Still, you can find debs here: https://github.com/brendonjkding/brendonjkding.github.io/tree/master/debs
