### ISSUE TITLE
hi sir, thank you for the tweak.

### ISSUE THREAD

**Issue by dualra1n** [brendonjkding/Unity60FPS#6]
hello sir, what do you think about creating new ios for payers that ios will get much more fps? I think deleting some service that spends a lot of ram or processor and installing some tweaks. is only a idea xd and do you think that would work ?

look this is my project https://github.com/edwin170/dualboot-ios-15-with-14-script that install 2 version of ios in one device and I believe that would be great a system operative mod like windows mod. thank you sir

**Comment by brendonjkding** [comment]
I think we already can disable some daemons using iCleaner?

**Comment by edwin170** [comment]
> I think we already can disable some daemons using iCleaner?

Mmm that is great I will try and what daemon do you you think are ineccesary or are less important and spend a lot of ram sir ?

**Comment by brendonjkding** [comment]
You will get a description prompt about each daemon(s) when tapping it in iCleaner. 

I think a large part of them are unnecessary, but I don't know how much resources they consume. 

Actually I seldom play games on iOS and the only one I am playing is not performance demanding, so I have little experiences in these things.

**Comment by edwin170** [comment]
> You will get a description prompt about each daemon(s) when tapping it in iCleaner. 
> 
> 
> 
> I think a large part of them are unnecessary, but I don't know how much resources they consume. 
> 
> 
> 
> Actually I seldom play games on iOS and the only one I am playing is not performance demanding, so I have little experiences in these things.

Ok sir very thank you
