### ISSUE TITLE
Convert tweak to TrollStore or injectable deb

### ISSUE THREAD

**Issue by imod-commission** [brendonjkding/Unity60FPS#8]
Hello, would it be possible to update this tweak into an injectable deb into ipa, or as a TrollStore ipa since tweak injection into unmodified apps installed from app store is now possible via CoreTrust 2, so that it can support up to newer iOS. The only ways to enable 60 FPS for unity games on iOS is either via this tweak or via Flex 3 which needs jailbreak, it would be amazing to use this tweak on newer versions, Thank you

**Comment by brendonjkding** [comment]
For this Tweak to work, the most important thing is inline hook. I don't know if TrollStore supports that.

**Comment by imod-commission** [comment]
Asked the jailbreak community and seems like the answer is no :( still, thank you for your reply

**Comment by imod-commission** [comment]
Hello, since the release of roothide bootstrap, is it possible to convert it to be compatible? It says not rootless when converting with roothide's converter tool so i assume this tweak is rootful jailbreak?

**Comment by imod-commission** [comment]
Sorry the one in releases doesnt work but the one from the repo converts. May i know where i can find the location of settings of the tweak (set fps, specify games etc)

**Comment by imod-commission** [comment]
Nevermind it is some setting i need to change it bootstrap. It works perfectly with your fps indicator tweak, thank you for the hard work!
